[ids]
*

[main]
leftmeta = playpause
open = leftmeta
pagedown = leftmeta
unknown = macro(leftmeta+leftshift+w)

[shift]
unknown = macro(leftmeta+leftshift+period)

[control]
unknown = macro(leftmeta+leftshift+comma)
